baseURL = 'https://nsd-public.yeojido.io/'
languageCode = 'ko-KR'
title = '낙성대 퍼블릭 오르: OR'

[params]
  isAdsEnabled = true
  adsTelegramId = "ggyuvely"

  description = '낙성대 퍼블릭 오르는 관악구 신림동 1432-73에서 운영되는 퍼블릭 업소로, 낙성대·사당 일대에서 회식과 접대 자리를 찾는 분들이 자주 찾는다.'
  author = '두리'
  datePublished = "2026-08-18T07:25:00+09:00"
  dateModified = "2026-08-18T07:25:00+09:00"
  [params.store]
  tel = "010-8306-5747"
  location = "낙성대"
  locationEn = "NSD"
  name = "오르"
  nameEn = "OR"
  category = "퍼블릭"
  categoryEn = "Public"
  address = "서울 관악구"
  googleMapSrc = "https://www.google.com/maps?q=서울+관악구&output=embed"
	[params.store.social.kakaoTalk]
	  id = ""
	  link = ""
	[params.store.social.telegram]
    id = ""
    link = ""

enableRobotsTXT = false
cleanDestinationDir = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
